#########
# PROJECT
#########

# Replace the values here with your project` information.
project:
  # The name of the organisation or entity that owns this project
  organisation: "Éditions Vodary Paris"
  # A live web address for the organisation
  url: "https://vodary.fias.fr"
  # The default contact email address
  email: "electricbook.vodary@fias.fr"
  # The name of the project of books in this folder.
  name: "Vodary Paris"
  # A one-liner about this project. Useful for Open Graph metadata.
  description: "Online reading platform of the open access publisher Vodary Paris."
  # The logo of the organisation, saved web-ready in /assets
  logo: "Logo.png"
  # An image in /assets that stands for the project
  image: "cover.jpg"
  # Credit line, by default in the footer, overidden in locales.yml
  credit: "[Éditions Vodary Paris](https://vodary.fias.fr) recurs to the [Electric Book workflow](http://electricbook.works) to render its books."
  # Primary language code for this project as a whole
  language: "en"
  # App bundle ID unique across all app stores
  app-id: com.example.myapp
  # Version. You must change this with each app update
  version: "1.0.0"


########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes
## especially if they contain only numbers.

works:
  - directory: "book"
    title: "An Essay on the Principle of Population"
    subtitle: ""
    creator: "Thomas Malthus" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "Demography" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "An essay on the principle of population, as it affects the future improvement of society with remarks on the speculations of Mr. Godwin, M. Condorcet, and other writers." # E.g. the blurb
    publisher: "Scientia Rerum, academic publishers, Paris" # E.g. the publisher, imprint or brand name
    publisher-url: "https://fias.fr/publishing"
    date: "1798-01-31" # YYYY-MM-DD e.g. publication date
    modified: "2018-10-08" # YYYY-MM-DD e.g. date of last revision
    type: "Scientific essay" # e.g. Novel, Poetry, Memoir
    identifier: "979-10-97005-00-9" # e.g. ISBN or UUID
    source: "" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "" #"All rights reserved. No part of this book may be reproduced or transmitted in any form or by any electronic or mechanical means, including photocopying and recording, or any other information storage or retrieval system, without written permission from the publisher." # e.g. a copyright statement
    image: "cover.jpg"
    products: # Metadata for each product for this title (only use values that override parent metadata)
      web:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01": "Chapter One"
          - "02": "Chapter Two"
          - "xx00.md"
          - "xx01.md"
          - "xx02.md"
          - "xx03.md"
          - "xx04.md"
          - "xx05.md"
          - "xx06.md"
          - "xx07.md"
          - "xx08.md"
          - "xx09.md"
          - "xx10.md"
          - "xx11.md"
          - "xx12.md"
          - "xx13.md"
          - "xx14.md"
          - "xx15.md"
          - "xx16.md"
          - "xx17.md"
          - "xx18.md"
          - "xx19.md"
          - "xx20.md"
          - "xx21.md"
          - "xx22.md"
          - "xx23.md"
          - "xx24.md"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children: 
              - label: "Subsection"
                file: "02"
                id: "example-id"
          - label: "xx00.md"
            file: "xx00.md"
          - label: "xx01.md"
            file: "xx01.md"
          - label: "xx02.md"
            file: "xx02.md"
          - label: "xx03.md"
            file: "xx03.md"
          - label: "xx04.md"
            file: "xx04.md"
          - label: "xx05.md"
            file: "xx05.md"
          - label: "xx06.md"
            file: "xx06.md"
          - label: "xx07.md"
            file: "xx07.md"
          - label: "xx08.md"
            file: "xx08.md"
          - label: "xx09.md"
            file: "xx09.md"
          - label: "xx10.md"
            file: "xx10.md"
          - label: "xx11.md"
            file: "xx11.md"
          - label: "xx12.md"
            file: "xx12.md"
          - label: "xx13.md"
            file: "xx13.md"
          - label: "xx14.md"
            file: "xx14.md"
          - label: "xx15.md"
            file: "xx15.md"
          - label: "xx16.md"
            file: "xx16.md"
          - label: "xx17.md"
            file: "xx17.md"
          - label: "xx18.md"
            file: "xx18.md"
          - label: "xx19.md"
            file: "xx19.md"
          - label: "xx20.md"
            file: "xx20.md"
          - label: "xx21.md"
            file: "xx21.md"
          - label: "xx22.md"
            file: "xx22.md"
          - label: "xx23.md"
            file: "xx23.md"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
